// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

#include "service.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace TINYKV {
class ReqKeyDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ReqKey>
      _instance;
} _ReqKey_default_instance_;
class ReqKeyValueDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ReqKeyValue>
      _instance;
} _ReqKeyValue_default_instance_;
class RespValueDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<RespValue>
      _instance;
} _RespValue_default_instance_;
}  // namespace TINYKV
namespace protobuf_service_2eproto {
static void InitDefaultsReqKey() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::TINYKV::_ReqKey_default_instance_;
    new (ptr) ::TINYKV::ReqKey();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::TINYKV::ReqKey::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ReqKey =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsReqKey}, {}};

static void InitDefaultsReqKeyValue() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::TINYKV::_ReqKeyValue_default_instance_;
    new (ptr) ::TINYKV::ReqKeyValue();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::TINYKV::ReqKeyValue::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ReqKeyValue =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsReqKeyValue}, {}};

static void InitDefaultsRespValue() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::TINYKV::_RespValue_default_instance_;
    new (ptr) ::TINYKV::RespValue();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::TINYKV::RespValue::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_RespValue =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsRespValue}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_ReqKey.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ReqKeyValue.base);
  ::google::protobuf::internal::InitSCC(&scc_info_RespValue.base);
}

::google::protobuf::Metadata file_level_metadata[3];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::TINYKV::ReqKey, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::TINYKV::ReqKey, qid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::TINYKV::ReqKey, key_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::TINYKV::ReqKeyValue, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::TINYKV::ReqKeyValue, qid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::TINYKV::ReqKeyValue, key_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::TINYKV::ReqKeyValue, value_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::TINYKV::RespValue, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::TINYKV::RespValue, status_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::TINYKV::RespValue, value_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::TINYKV::ReqKey)},
  { 7, -1, sizeof(::TINYKV::ReqKeyValue)},
  { 15, -1, sizeof(::TINYKV::RespValue)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::TINYKV::_ReqKey_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::TINYKV::_ReqKeyValue_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::TINYKV::_RespValue_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "service.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 3);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\rservice.proto\022\006TINYKV\"\"\n\006ReqKey\022\013\n\003qid"
      "\030\001 \001(\003\022\013\n\003key\030\002 \003(\t\"6\n\013ReqKeyValue\022\013\n\003qi"
      "d\030\001 \001(\003\022\013\n\003key\030\002 \003(\t\022\r\n\005value\030\003 \003(\t\"*\n\tR"
      "espValue\022\016\n\006status\030\001 \001(\005\022\r\n\005value\030\002 \003(\t2"
      "k\n\tKVService\022*\n\003Get\022\016.TINYKV.ReqKey\032\021.TI"
      "NYKV.RespValue\"\000\0222\n\006Insert\022\023.TINYKV.ReqK"
      "eyValue\032\021.TINYKV.RespValue\"\000b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 276);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "service.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_service_2eproto
namespace TINYKV {

// ===================================================================

void ReqKey::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ReqKey::kQidFieldNumber;
const int ReqKey::kKeyFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ReqKey::ReqKey()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_service_2eproto::scc_info_ReqKey.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:TINYKV.ReqKey)
}
ReqKey::ReqKey(const ReqKey& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      key_(from.key_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  qid_ = from.qid_;
  // @@protoc_insertion_point(copy_constructor:TINYKV.ReqKey)
}

void ReqKey::SharedCtor() {
  qid_ = GOOGLE_LONGLONG(0);
}

ReqKey::~ReqKey() {
  // @@protoc_insertion_point(destructor:TINYKV.ReqKey)
  SharedDtor();
}

void ReqKey::SharedDtor() {
}

void ReqKey::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ReqKey::descriptor() {
  ::protobuf_service_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_service_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ReqKey& ReqKey::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_service_2eproto::scc_info_ReqKey.base);
  return *internal_default_instance();
}


void ReqKey::Clear() {
// @@protoc_insertion_point(message_clear_start:TINYKV.ReqKey)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  key_.Clear();
  qid_ = GOOGLE_LONGLONG(0);
  _internal_metadata_.Clear();
}

bool ReqKey::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:TINYKV.ReqKey)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int64 qid = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &qid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated string key = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_key()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->key(this->key_size() - 1).data(),
            static_cast<int>(this->key(this->key_size() - 1).length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "TINYKV.ReqKey.key"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:TINYKV.ReqKey)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:TINYKV.ReqKey)
  return false;
#undef DO_
}

void ReqKey::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:TINYKV.ReqKey)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 qid = 1;
  if (this->qid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->qid(), output);
  }

  // repeated string key = 2;
  for (int i = 0, n = this->key_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->key(i).data(), static_cast<int>(this->key(i).length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "TINYKV.ReqKey.key");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->key(i), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:TINYKV.ReqKey)
}

::google::protobuf::uint8* ReqKey::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:TINYKV.ReqKey)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 qid = 1;
  if (this->qid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->qid(), target);
  }

  // repeated string key = 2;
  for (int i = 0, n = this->key_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->key(i).data(), static_cast<int>(this->key(i).length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "TINYKV.ReqKey.key");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(2, this->key(i), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:TINYKV.ReqKey)
  return target;
}

size_t ReqKey::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:TINYKV.ReqKey)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated string key = 2;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->key_size());
  for (int i = 0, n = this->key_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->key(i));
  }

  // int64 qid = 1;
  if (this->qid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->qid());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ReqKey::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:TINYKV.ReqKey)
  GOOGLE_DCHECK_NE(&from, this);
  const ReqKey* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ReqKey>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:TINYKV.ReqKey)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:TINYKV.ReqKey)
    MergeFrom(*source);
  }
}

void ReqKey::MergeFrom(const ReqKey& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:TINYKV.ReqKey)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  key_.MergeFrom(from.key_);
  if (from.qid() != 0) {
    set_qid(from.qid());
  }
}

void ReqKey::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:TINYKV.ReqKey)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReqKey::CopyFrom(const ReqKey& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:TINYKV.ReqKey)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReqKey::IsInitialized() const {
  return true;
}

void ReqKey::Swap(ReqKey* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ReqKey::InternalSwap(ReqKey* other) {
  using std::swap;
  key_.InternalSwap(CastToBase(&other->key_));
  swap(qid_, other->qid_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ReqKey::GetMetadata() const {
  protobuf_service_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_service_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ReqKeyValue::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ReqKeyValue::kQidFieldNumber;
const int ReqKeyValue::kKeyFieldNumber;
const int ReqKeyValue::kValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ReqKeyValue::ReqKeyValue()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_service_2eproto::scc_info_ReqKeyValue.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:TINYKV.ReqKeyValue)
}
ReqKeyValue::ReqKeyValue(const ReqKeyValue& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      key_(from.key_),
      value_(from.value_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  qid_ = from.qid_;
  // @@protoc_insertion_point(copy_constructor:TINYKV.ReqKeyValue)
}

void ReqKeyValue::SharedCtor() {
  qid_ = GOOGLE_LONGLONG(0);
}

ReqKeyValue::~ReqKeyValue() {
  // @@protoc_insertion_point(destructor:TINYKV.ReqKeyValue)
  SharedDtor();
}

void ReqKeyValue::SharedDtor() {
}

void ReqKeyValue::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ReqKeyValue::descriptor() {
  ::protobuf_service_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_service_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ReqKeyValue& ReqKeyValue::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_service_2eproto::scc_info_ReqKeyValue.base);
  return *internal_default_instance();
}


void ReqKeyValue::Clear() {
// @@protoc_insertion_point(message_clear_start:TINYKV.ReqKeyValue)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  key_.Clear();
  value_.Clear();
  qid_ = GOOGLE_LONGLONG(0);
  _internal_metadata_.Clear();
}

bool ReqKeyValue::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:TINYKV.ReqKeyValue)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int64 qid = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &qid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated string key = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_key()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->key(this->key_size() - 1).data(),
            static_cast<int>(this->key(this->key_size() - 1).length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "TINYKV.ReqKeyValue.key"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated string value = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_value()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->value(this->value_size() - 1).data(),
            static_cast<int>(this->value(this->value_size() - 1).length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "TINYKV.ReqKeyValue.value"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:TINYKV.ReqKeyValue)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:TINYKV.ReqKeyValue)
  return false;
#undef DO_
}

void ReqKeyValue::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:TINYKV.ReqKeyValue)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 qid = 1;
  if (this->qid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->qid(), output);
  }

  // repeated string key = 2;
  for (int i = 0, n = this->key_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->key(i).data(), static_cast<int>(this->key(i).length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "TINYKV.ReqKeyValue.key");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->key(i), output);
  }

  // repeated string value = 3;
  for (int i = 0, n = this->value_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->value(i).data(), static_cast<int>(this->value(i).length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "TINYKV.ReqKeyValue.value");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->value(i), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:TINYKV.ReqKeyValue)
}

::google::protobuf::uint8* ReqKeyValue::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:TINYKV.ReqKeyValue)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 qid = 1;
  if (this->qid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->qid(), target);
  }

  // repeated string key = 2;
  for (int i = 0, n = this->key_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->key(i).data(), static_cast<int>(this->key(i).length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "TINYKV.ReqKeyValue.key");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(2, this->key(i), target);
  }

  // repeated string value = 3;
  for (int i = 0, n = this->value_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->value(i).data(), static_cast<int>(this->value(i).length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "TINYKV.ReqKeyValue.value");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(3, this->value(i), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:TINYKV.ReqKeyValue)
  return target;
}

size_t ReqKeyValue::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:TINYKV.ReqKeyValue)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated string key = 2;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->key_size());
  for (int i = 0, n = this->key_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->key(i));
  }

  // repeated string value = 3;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->value_size());
  for (int i = 0, n = this->value_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->value(i));
  }

  // int64 qid = 1;
  if (this->qid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->qid());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ReqKeyValue::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:TINYKV.ReqKeyValue)
  GOOGLE_DCHECK_NE(&from, this);
  const ReqKeyValue* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ReqKeyValue>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:TINYKV.ReqKeyValue)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:TINYKV.ReqKeyValue)
    MergeFrom(*source);
  }
}

void ReqKeyValue::MergeFrom(const ReqKeyValue& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:TINYKV.ReqKeyValue)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  key_.MergeFrom(from.key_);
  value_.MergeFrom(from.value_);
  if (from.qid() != 0) {
    set_qid(from.qid());
  }
}

void ReqKeyValue::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:TINYKV.ReqKeyValue)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReqKeyValue::CopyFrom(const ReqKeyValue& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:TINYKV.ReqKeyValue)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReqKeyValue::IsInitialized() const {
  return true;
}

void ReqKeyValue::Swap(ReqKeyValue* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ReqKeyValue::InternalSwap(ReqKeyValue* other) {
  using std::swap;
  key_.InternalSwap(CastToBase(&other->key_));
  value_.InternalSwap(CastToBase(&other->value_));
  swap(qid_, other->qid_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ReqKeyValue::GetMetadata() const {
  protobuf_service_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_service_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void RespValue::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int RespValue::kStatusFieldNumber;
const int RespValue::kValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

RespValue::RespValue()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_service_2eproto::scc_info_RespValue.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:TINYKV.RespValue)
}
RespValue::RespValue(const RespValue& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      value_(from.value_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  status_ = from.status_;
  // @@protoc_insertion_point(copy_constructor:TINYKV.RespValue)
}

void RespValue::SharedCtor() {
  status_ = 0;
}

RespValue::~RespValue() {
  // @@protoc_insertion_point(destructor:TINYKV.RespValue)
  SharedDtor();
}

void RespValue::SharedDtor() {
}

void RespValue::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* RespValue::descriptor() {
  ::protobuf_service_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_service_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const RespValue& RespValue::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_service_2eproto::scc_info_RespValue.base);
  return *internal_default_instance();
}


void RespValue::Clear() {
// @@protoc_insertion_point(message_clear_start:TINYKV.RespValue)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  value_.Clear();
  status_ = 0;
  _internal_metadata_.Clear();
}

bool RespValue::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:TINYKV.RespValue)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 status = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &status_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated string value = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_value()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->value(this->value_size() - 1).data(),
            static_cast<int>(this->value(this->value_size() - 1).length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "TINYKV.RespValue.value"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:TINYKV.RespValue)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:TINYKV.RespValue)
  return false;
#undef DO_
}

void RespValue::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:TINYKV.RespValue)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 status = 1;
  if (this->status() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->status(), output);
  }

  // repeated string value = 2;
  for (int i = 0, n = this->value_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->value(i).data(), static_cast<int>(this->value(i).length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "TINYKV.RespValue.value");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->value(i), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:TINYKV.RespValue)
}

::google::protobuf::uint8* RespValue::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:TINYKV.RespValue)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 status = 1;
  if (this->status() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->status(), target);
  }

  // repeated string value = 2;
  for (int i = 0, n = this->value_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->value(i).data(), static_cast<int>(this->value(i).length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "TINYKV.RespValue.value");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(2, this->value(i), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:TINYKV.RespValue)
  return target;
}

size_t RespValue::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:TINYKV.RespValue)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated string value = 2;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->value_size());
  for (int i = 0, n = this->value_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->value(i));
  }

  // int32 status = 1;
  if (this->status() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->status());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void RespValue::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:TINYKV.RespValue)
  GOOGLE_DCHECK_NE(&from, this);
  const RespValue* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const RespValue>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:TINYKV.RespValue)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:TINYKV.RespValue)
    MergeFrom(*source);
  }
}

void RespValue::MergeFrom(const RespValue& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:TINYKV.RespValue)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  value_.MergeFrom(from.value_);
  if (from.status() != 0) {
    set_status(from.status());
  }
}

void RespValue::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:TINYKV.RespValue)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RespValue::CopyFrom(const RespValue& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:TINYKV.RespValue)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RespValue::IsInitialized() const {
  return true;
}

void RespValue::Swap(RespValue* other) {
  if (other == this) return;
  InternalSwap(other);
}
void RespValue::InternalSwap(RespValue* other) {
  using std::swap;
  value_.InternalSwap(CastToBase(&other->value_));
  swap(status_, other->status_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata RespValue::GetMetadata() const {
  protobuf_service_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_service_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace TINYKV
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::TINYKV::ReqKey* Arena::CreateMaybeMessage< ::TINYKV::ReqKey >(Arena* arena) {
  return Arena::CreateInternal< ::TINYKV::ReqKey >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::TINYKV::ReqKeyValue* Arena::CreateMaybeMessage< ::TINYKV::ReqKeyValue >(Arena* arena) {
  return Arena::CreateInternal< ::TINYKV::ReqKeyValue >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::TINYKV::RespValue* Arena::CreateMaybeMessage< ::TINYKV::RespValue >(Arena* arena) {
  return Arena::CreateInternal< ::TINYKV::RespValue >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
